### ISSUE TITLE
按照opencore6.8的文档，用Rufus+macrecovery.py下载的文件引导读条几秒后黑屏。。

### ISSUE THREAD

**Issue by hdchieh** [chencaidy/Hackintosh-OC-Optiplex-5060MFF#2]
硬件和你的一样
按照6.8文档操作rufus
bios都改了（不在bios选项里面的两个也改了。

已经进入了恢复界面，白苹果logo读条，十秒钟左右黑屏。
想问问大佬大概是什么原因，大概。明天用完整的镜像试一下。。

**Comment by hdchieh** [comment]
我明天看一下opencore debugging那个小结再试试。。

**Comment by chencaidy** [comment]
看问题表现不像是OC导致
我这只有1080P显示器，在此条件下测试通过，建议更换显示器尝试
再继续反馈跟进

**Comment by hdchieh** [comment]
发现了 这台机器只能DP直连 或者转HDMI，或者转VGA，不能转DVI

**Comment by hdchieh** [comment]
> 发现了 这台机器只能DP直连 或者转HDMI，或者转VGA，不能转DVI

我这是蠢死了
