### ISSUE TITLE
用了你的efi 目前除了蓝牙一切完美 蓝牙连不了新设备

### ISSUE THREAD

**Issue by hyuanye-Yuri** [chencaidy/Hackintosh-OC-Optiplex-5060MFF#5]
用的网卡是94360z4
也是免驱wifi 蓝牙用的小兵黑果的BrcmBluetoothInjector.kext
按着他的说法放进去config里添加一下
但是我蓝牙能搜到却不能添加。一直找不到原因
说它没用吧可是之前卖掉的cs2的网卡连过的设备电脑记住了 又能连 连不了新的设备

**Comment by hyuanye-Yuri** [comment]
还有你的电脑用的是外接的小天线吗 我的小辣椒信号没有满格 也不知道为啥

**Comment by chencaidy** [comment]
删除已经配对的设备，重建kexts
